apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-app
  namespace: board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-app
  template:
    metadata:
      labels:
        app: board-app
    spec:
      containers:
        - name: jboss
          image: default-route-openshift-image-registry.apps.ext2.mtp.local/board/eap74-openjdk17-openshift-rhel8:2025-03-13-14-15-32
          ports:
            - containerPort: 8080
          env:
            - name: WILDFLY_BIND
              value: "0.0.0.0"
            - name: WILDFLY_PORT
              value: "8080"
            - name: WILDFLY_ENABLE_HTTPS
              value: "false"
            - name: WILDFLY_ENABLE_HTTP
              value: "true"
          command: ["/bin/sh", "-c"]
          args:
            - "echo '<formatter name=\"CONSOLE-FORMATTER\"><pattern-formatter pattern=\"%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%E%n\"/></formatter>' > /opt/eap/standalone/configuration/standalone-openshift.xml && echo 'formatter.CONSOLE-FORMATTER=org.jboss.logmanager.formatters.PatternFormatter' > /opt/eap/standalone/configuration/logging.properties && echo 'formatter.CONSOLE-FORMATTER.pattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%E%n' >> /opt/eap/standalone/configuration/logging.properties && /opt/eap/bin/standalone.sh -b 0.0.0.0 --server-config=standalone-openshift.xml"
