apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-app
  namespace: board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-app
  template:
    metadata:
      labels:
        app: board-app
    spec:
      containers:
        - name: jboss
          image: default-route-openshift-image-registry.apps.ext2.mtp.local/board/eap74-openjdk17-openshift-rhel8:2025-03-14-09-22-21
          ports:
            - containerPort: 8080
          env:
            - name: WILDFLY_BIND
              value: "0.0.0.0"
            - name: WILDFLY_PORT
              value: "8080"
            - name: WILDFLY_ENABLE_HTTPS
              value: "false"
            - name: WILDFLY_ENABLE_HTTP
              value: "true"
            - name: WILDFLY_SERVER_CONFIG
              value: "standalone-openshift.xml"
          command: ["/bin/sh", "-c"]
          args:
            - |
              LOGGING_CONFIG="/opt/eap/standalone/configuration/logging.properties"
              XML_CONFIG="/opt/eap/standalone/configuration/standalone-openshift.xml"

              echo "==== Step 1: Configuring JBoss Node Name (Max 23 chars) ===="
              export JBOSS_NODE_NAME="node-$(hostname | cut -c1-23)"
              
              echo "==== Step 2: Removing activemq-rar.rar to prevent deployment failure ===="
              rm -f /opt/eap/standalone/deployments/activemq-rar.rar
              rm -f /opt/eap/standalone/deployments/activemq-rar.rar.deployed

              echo "==== Step 3: Starting JBoss in background ===="
              /opt/eap/bin/standalone.sh -b 0.0.0.0 --server-config=standalone-openshift.xml &

              echo "==== Step 4: Waiting for JBoss to be ready ===="
              RETRY=0
              until /opt/eap/bin/jboss-cli.sh --connect --commands=":read-attribute(name=server-state)" | grep -q "running"; do
                if [ $RETRY -ge 10 ]; then
                  echo "ERROR: JBoss did not start in time."
                  exit 1
                fi
                echo "Waiting for JBoss to start... ($RETRY/10)"
                sleep 5
                RETRY=$((RETRY+1))
              done

              echo "==== Step 5: Setting up JBoss logging configuration ===="
              cat << EOF > $LOGGING_CONFIG
              formatter.CONSOLE-FORMATTER=org.jboss.logmanager.formatters.PatternFormatter
              formatter.CONSOLE-FORMATTER.pattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%E%n
              EOF

              echo "==== Step 6: Enabling JBoss Management Console ===="
              /opt/eap/bin/jboss-cli.sh --connect --commands="/core-service=management/management-interface=http-interface:write-attribute(name=console-enabled,value=true)"

              echo "==== Step 7: Fixing transaction dependencies ===="
              /opt/eap/bin/jboss-cli.sh --connect <<EOF
              /subsystem=transactions:write-attribute(name=node-identifier,value="node-$(hostname | cut -c1-23)")
              reload
              EOF

              echo "==== Step 8: Keeping JBoss Running ===="
              wait

