apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-app
  namespace: board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-app
  template:
    metadata:
      labels:
        app: board-app
    spec:
      containers:
        - name: jboss
          image: default-route-openshift-image-registry.apps.ext2.mtp.local/board/eap74-openjdk17-openshift-rhel8:2025-03-14-09-50-51
          ports:
            - containerPort: 8080
          env:
            - name: WILDFLY_ENABLE_HTTPS
              value: "false"
            - name: WILDFLY_ENABLE_HTTP
              value: "true"
          command: ["/opt/jboss/container/wildfly/s2i/run.sh"]
