apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: board-route
  namespace: board
  labels:
    type: sharded
spec:
  host: cys.board.com
  to:
    kind: Service
    name: board-service
  port:
    targetPort: 8080
  tls:
    termination: edge
